### ISSUE TITLE
Deployed branch does not show if tag has already been deployed

### ISSUE THREAD

**Issue by jelmerdemaat** [markri/organist#5]
In an applications Dashboard, after a branch is deployed (e.g. _develop_) but previously a tag has been deployed, the branch name is not visible. The previous tag is still in place.

I guess it has something to do with this logic in [dashboard.html.twig](https://github.com/markri/organist/blob/master/src/Netvlies/Bundle/PublishBundle/Resources/views/Application/dashboard.html.twig#L69).

**Comment by markri** [comment]
Good one!, will fix ASAP
