### ISSUE TITLE
Ampersand (&) character replaced by #mysqlpw# in db password field

### ISSUE THREAD

**Issue by Mortek** [markri/organist#7]
If you create password with a **&** in it, the **&** will be removed on deploy and replaced with **#mysqlpw#**.  For example: If you fill in the following password in Organist: **WJBF&WEUBWE** the following password will be inserted in the settings.php file on the server: **WJBF#mysqlpw#WEUBWE**. Could be the case with all fields that are inserted like this..

**Comment by markri** [comment]
After some research, this doesnt seem to be an Organist issue. This is due to the internal layer "Capinist" (the extra tasks on top of Capistrano). Internally it uses "sed" to replace variables. Seems this needs to be escaped, before "sedding". I created an issue on the appropriate repository
